# Generated by Django 4.2.5 on 2023-09-05 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Todo',
        ),
    ]
